services:
  mongo:
    image: mongo:latest
    container_name: kanban-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=kanban_db

volumes:
  mongo-data:
